version: '3.7'
services:
  app:
    depends_on: 
      - db
    container_name: hotbox-app
    build:
      context: .
      dockerfile: Dockerfile
    image: hotbox-app
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - hotbox-network
  db: # TODO: Do retry logic in the code or use wait-for-it !!
    container_name: hotbox-db
    image: postgres #TODO: lookup latest image
    expose:
      - 5432
    ports:
      # machine:container
      - 5001:5432
    env_file:
      - .env
    networks:
      - hotbox-network
    volumes:
      - database-data:/var/lib/postgresql/data/

networks:
  hotbox-network:
    name: hotbox-network
    driver: bridge

volumes:
  database-data: