version: '3.7'
services:
  app:
    depends_on: 
      - db
    container_name: hotbox-app
    build:
      context: .
      dockerfile: Dockerfile
    image: hotbox-app
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - hotbox-network
  db:
    container_name: hotbox-db
    image: postgres:12.0-alpine
    expose:
      - 5432
    ports:
      - 4001:5432
    env_file:
      - .env
    networks:
      - hotbox-network
networks:
  hotbox-network:
    name: hotbox-network
    driver: bridge
